### ISSUE TITLE
Problematic wordlists

### ISSUE THREAD

**Issue by tevador** [tevador/polyseed#1]
The library currently uses the BIP-39 wordlists without changes.

However, some of the lists have issues:

1. The Czech, Spanish and Japanese wordlists were not correcly sorted by their authors, which means that efficient binary seach cannot be used (polyseed uses linear search for these languages, which is about 100x slower).
2. The English list contains the word 'satoshi', which has no meaning outside of Bitcoin.

There might not be a compelling reason to stay compatible with the BIP-39 wordlists, so there is the option to fix the above issues before integrating the library.

**Comment by tevador** [comment]
The first point was resolved in e2422254260f38347e3c28e9bcc11dd981d40ba1

For 2., here are two candidate words that could replace "satoshi":

```
sapphire
sarcasm
```
Both of them would go between "sand" and "satisfy" because there are no good candidates that could go between "satisfy" and "sauce". This change would thus affect 2 words in the wordlist.

**Comment by nanostos** [comment]
As a casual observer, I'd suggest that BIP39 already occupies to much mind space that the word satoshi is not sufficiently bothersome to overcome the potential misunderstandings coming from having an 'almost-BIP39' wordlist. It's more confusing than having a totally distict one.

Satoshi might not be directly involved with Monero, but he did really kick off blockchain-based currencies. It's sort of like the Tesla company's name, even though Nikola didn't actually contribute to that company. So, I think it seems acceptable.

**Comment by tevador** [comment]
The conclusion of this issue is:

1. The word order in the Czech, Spanish and Japanese wordlists has been fixed.
2. The word 'satoshi' stays in the English wordlist.
